'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import type { ReactNode } from 'react';
export type NavItem = { href: string; label: string };
function Navigation({ items }: { items: NavItem[] }) { const pathname = usePathname(); return <nav aria-label="Primary navigation" className="flex items-center gap-1 overflow-x-auto">{items.map((item) => { const active = pathname === item.href || (item.href !== '/teacher/review' && pathname.startsWith(`${item.href}/`)); return <Link key={item.href} href={item.href} aria-current={active ? 'page' : undefined} className={`rounded-lg px-3 py-2 text-sm font-medium transition-colors ${active ? 'bg-slate-100 text-slate-950' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-950'}`}>{item.label}</Link>; })}</nav>; }
function Brand() { return <Link href="/" className="flex shrink-0 items-center gap-2" aria-label="BAREA home"><span className="grid size-9 place-items-center rounded-xl bg-slate-950 text-sm font-extrabold tracking-tight text-white shadow-sm">B</span><span className="text-lg font-bold tracking-tight text-slate-950">BAREA</span></Link>; }
export function PublicShell({ children }: { children: ReactNode }) { return <div className="min-h-screen bg-[var(--barea-bg)] text-[var(--barea-text-primary)]"><header className="border-b border-[var(--barea-border)] bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><Brand /><Link href="/teacher/quizzes" className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100">Host a quiz</Link></div></header><main>{children}</main></div>; }
export function TeacherShell({ children }: { children: ReactNode }) { const items: NavItem[] = [{ href: '/teacher/quizzes', label: 'Quizzes' }, { href: '/teacher/review', label: 'Review' }]; return <div className="min-h-screen bg-[var(--barea-bg)] text-[var(--barea-text-primary)]"><header className="sticky top-0 z-20 border-b border-[var(--barea-border)] bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-7xl flex-wrap items-center gap-4 px-4 py-2 sm:px-6 lg:px-8"><Brand /><span className="hidden h-6 w-px bg-slate-200 sm:block" aria-hidden="true" /><span className="hidden text-sm font-medium text-slate-500 sm:block">Teacher workspace</span><div className="ml-auto"><Navigation items={items} /></div></div></header><main className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 lg:px-8">{children}</main><footer className="border-t border-slate-200 bg-white py-5"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 text-xs text-slate-500 sm:px-6 lg:px-8"><span>BAREA Church Education Platform</span><span>Server-authoritative</span></div></footer></div>; }
export function ParticipantShell({ children }: { children: ReactNode }) { return <div className="min-h-screen bg-[var(--barea-bg)] text-[var(--barea-text-primary)]"><header className="border-b border-[var(--barea-border)] bg-white"><div className="mx-auto flex h-14 max-w-xl items-center justify-center px-4"><Brand /></div></header><main className="mx-auto w-full max-w-xl px-4 py-6 sm:px-6">{children}</main></div>; }
